homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
  keepalive: 60
  password: FuckTheMqtt66
  reject_unauthorized: true
  user: mqtt
  version: 4
serial:
  port: \\.\COM4
advanced:
  pan_id: 44011
  channel: 14
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  last_seen: ISO_8601_local
  log_level: info
device_options:
  legacy: false
frontend:
  port: 8080
devices: devices.yaml
external_converters:
  #- dht11_ptvo.js
  - MIKE.CC2530.IAR.js
  #- DIYRuZRT.js
  #- MIKE.CC2530.js
  #- MIKE.ESP32-C3.js
  #- MIKE.ESP32-C6.js
  #- MIKE.ESP32C6_CO2.js
availability: false
